kind: Pod
apiVersion: v1
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
     # soft limit
      requests:
        memory: "70Mi"
        cpu: "100m"
      # hard limit
      limits:
        memory: "140Mi"
        cpu: "150m"

