kind: Pod
apiVersion: v1
metadata: 
  name: sa-demo
  namespace: expense
spec:
# one Pod can contain multiple containers
  serviceaccount: expense-mysql-secret
  
  containers:
  - name: nginx
    image: nginx